//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4_1.Common.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAsset
    {
        public long AssetID { get; set; }
        public System.Guid ClientAccountID { get; set; }
        public System.Guid AssetHolderID { get; set; }
        public long TokensCount { get; set; }
    
        public virtual AssetHolder AssetHolder { get; set; }
        public virtual ClientAccount ClientAccount { get; set; }
    }
}
