//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRPOEntities : DbContext
    {
        public TRPOEntities()
            : base("name=TRPOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountAsset> AccountAssets { get; set; }
        public virtual DbSet<AssetHolder> AssetHolders { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientAccount> ClientAccounts { get; set; }
    }
}
